export const translations = {
  English: {
    dashboard: "Dashboard",
    users: "Users",
    bookings: "Bookings",
    species: "Species",
    reports: "Global Reports",
    settings: "Settings",
    profile: "Profile",
    logout: "Logout",
    welcome: "Welcome back",
    statusOptimal: "Optimal",
    search: "Universal Search...",
    myAccount: "My Account",
    appearance: "Appearance",
    system: "System",
    privacy: "Privacy & Security",
    saveChanges: "Save All Changes",
    revert: "Reset to Defaults",
    darkMode: "Dark Mode",
    language: "Language",
    timeZone: "Time Zone",
    dateFormat: "Date Format",
  },
  Kinyarwanda: {
    dashboard: "Incamake",
    users: "Abakoresha",
    bookings: "Kubaka",
    species: "Ubwoko",
    reports: "Raporo Rusange",
    settings: "Igenamiterere",
    profile: "Umwirondoro",
    logout: "Sohoka",
    welcome: "Murakaza neza",
    statusOptimal: "Bisanzwe",
    search: "Shakisha...",
    myAccount: "Konti Yanjye",
    appearance: "Isura",
    system: "Sisitemu",
    privacy: "Umutekano",
    saveChanges: "Bika",
    revert: "Gusubira ku miterere",
    darkMode: "Uburyo bw'Ijoro",
    language: "Ururimi",
    timeZone: "Amasaha",
    dateFormat: "Imiterere y'Itariki",
  },
  French: {
    dashboard: "Tableau de Bord",
    users: "Utilisateurs",
    bookings: "Réservations",
    species: "Espèces",
    reports: "Rapports Globaux",
    settings: "Paramètres",
    profile: "Profil",
    logout: "Déconnexion",
    welcome: "Bienvenue",
    statusOptimal: "Optimal",
    search: "Recherche Universelle...",
    myAccount: "Mon Compte",
    appearance: "Apparence",
    system: "Système",
    privacy: "Confidentialité",
    saveChanges: "Enregistrer",
    revert: "Réinitialiser",
    darkMode: "Mode Sombre",
    language: "Langue",
    timeZone: "Fuseau Horaire",
    dateFormat: "Format de Date",
  }
};
