export const translations = {
  English: {
    dashboard: "Dashboard",
    users: "Users",
    bookings: "Bookings",
    species: "Species",
    reports: "Global Reports",
    settings: "Settings",
    profile: "Profile",
    logout: "Logout",
    welcome: "Welcome back",
    statusOptimal: "Optimal",
    search: "Universal Search...",
    myAccount: "My Account",
    appearance: "Appearance",
    system: "System",
    privacy: "Privacy & Security",
    saveChanges: "Save All Changes",
    revert: "Reset to Defaults",
    darkMode: "Dark Mode",
    language: "Language",
    timeZone: "Time Zone",
    dateFormat: "Date Format",
    // Dashboard content
    myVisits: "My Visits",
    upcoming: "Upcoming",
    ecoPoints: "Eco Points",
    saved: "Saved",
    history: "History",
    nextMonth: "Next Month",
    locations: "Locations",
    myReservations: "My Reservations",
    bookNewVisit: "Book New Visit",
    visitors: "Visitors",
    marshlandWatch: "Marshland Watch",
    exploreWiki: "Explore Wiki",
    scientificCapture: "Scientific Capture",
    fieldObservation: "Field Observation",
    capturedInMarshland: "Captured in the marshland ecosystem",
    myBookings: "My Bookings",
    checkAvailability: "Check Availability",
    approved: "APPROVED",
    pending: "PENDING",
    rejected: "REJECTED",
    cancelled: "CANCELLED",
  },
  Kinyarwanda: {
    dashboard: "Incamake",
    users: "Abakoresha",
    bookings: "Kubaka",
    species: "Ubwoko",
    reports: "Raporo Rusange",
    settings: "Igenamiterere",
    profile: "Umwirondoro",
    logout: "Sohoka",
    welcome: "Murakaza neza",
    statusOptimal: "Bisanzwe",
    search: "Shakisha...",
    myAccount: "Konti Yanjye",
    appearance: "Isura",
    system: "Sisitemu",
    privacy: "Umutekano",
    saveChanges: "Bika",
    revert: "Gusubira ku miterere",
    darkMode: "Uburyo bw'Ijoro",
    language: "Ururimi",
    timeZone: "Amasaha",
    dateFormat: "Imiterere y'Itariki",
    // Dashboard content
    myVisits: "Amazina Yanjye",
    upcoming: "Uza kugera",
    ecoPoints: "Amaponti y'Ecology",
    saved: "Abibumwe",
    history: "Amateka",
    nextMonth: "Ukwezi Kuzaza",
    locations: "Aho biherereye",
    myReservations: "Amabiko Yanjye",
    bookNewVisit: "Kubaka Urukurikane Ruphya",
    visitors: "Abagenzi",
    marshlandWatch: "Kureba Marshland",
    exploreWiki: "Kumenyesha Wiki",
    scientificCapture: "Kwiga Kwihangira",
    fieldObservation: "Kureba Mu Murima",
    capturedInMarshland: "Yafunzwe muri Marshland ecosystem",
    myBookings: "Amabiko Yanjye",
    checkAvailability: "Kureba Uburyo Bihari",
    approved: "YEMEWE",
    pending: "ITEGANYE",
    rejected: "KANZWE",
    cancelled: "KURWANYWE",
  },
  French: {
    dashboard: "Tableau de Bord",
    users: "Utilisateurs",
    bookings: "Réservations",
    species: "Espèces",
    reports: "Rapports Globaux",
    settings: "Paramètres",
    profile: "Profil",
    logout: "Déconnexion",
    welcome: "Bienvenue",
    statusOptimal: "Optimal",
    search: "Recherche Universelle...",
    myAccount: "Mon Compte",
    appearance: "Apparence",
    system: "Système",
    privacy: "Confidentialité",
    saveChanges: "Enregistrer",
    revert: "Réinitialiser",
    darkMode: "Mode Sombre",
    language: "Langue",
    timeZone: "Fuseau Horaire",
    dateFormat: "Format de Date",
    // Dashboard content
    myVisits: "Mes Visites",
    upcoming: "À Venir",
    ecoPoints: "Points Éco",
    saved: "Enregistrés",
    history: "Historique",
    nextMonth: "Le Mois Prochain",
    locations: "Lieux",
    myReservations: "Mes Réservations",
    bookNewVisit: "Réserver une Nouvelle Visite",
    visitors: "Visiteurs",
    marshlandWatch: "Surveillance Marécage",
    exploreWiki: "Explorer Wiki",
    scientificCapture: "Capture Scientifique",
    fieldObservation: "Observation sur le Terrain",
    capturedInMarshland: "Capturé dans l'écosystème marécageux",
    myBookings: "Mes Réservations",
    checkAvailability: "Vérifier la Disponibilité",
    approved: "APPROUVÉ",
    pending: "EN ATTENTE",
    rejected: "REJETÉ",
    cancelled: "ANNULÉ",
  }
};
