export const translations = {
  English: {
    dashboard: "Dashboard",
    users: "Users",
    bookings: "Bookings",
    species: "Species",
    reports: "Global Reports",
    settings: "Settings",
    profile: "Profile",
    logout: "Logout",
    welcome: "Welcome back",
    statusOptimal: "Optimal",
    search: "Universal Search...",
    myAccount: "My Account",
    appearance: "Appearance",
    system: "System",
    privacy: "Privacy & Security",
    saveChanges: "Save All Changes",
    revert: "Reset to Defaults",
    darkMode: "Dark Mode",
    language: "Language",
    timeZone: "Time Zone",
    dateFormat: "Date Format",
    // Dashboard content
    myVisits: "My Visits",
    upcoming: "Upcoming",
    ecoPoints: "Eco Points",
    saved: "Saved",
    history: "History",
    nextMonth: "Next Month",
    locations: "Locations",
    myReservations: "My Reservations",
    bookNewVisit: "Book New Visit",
    visitors: "Visitors",
    marshlandWatch: "Marshland Watch",
    exploreWiki: "Explore Wiki",
    scientificCapture: "Scientific Capture",
    fieldObservation: "Field Observation",
    capturedInMarshland: "Captured in the marshland ecosystem",
    myBookings: "My Bookings",
    checkAvailability: "Check Availability",
    approved: "APPROVED",
    pending: "PENDING",
    rejected: "REJECTED",
    cancelled: "CANCELLED",
    // Admin Dashboard
    totalUsers: "Total Users",
    activeUsers: "Active Users",
    systemHealth: "System Health",
    recentActivity: "Recent Activity",
    userManagement: "User Management",
    systemReports: "System Reports",
    galleryManagement: "Gallery Management",
    feedbackManagement: "Feedback Management",
    systemSettings: "System Settings",
    allUsers: "All Users",
    addUser: "Add User",
    editUser: "Edit User",
    deleteUser: "Delete User",
    role: "Role",
    status: "Status",
    email: "Email",
    lastLogin: "Last Login",
    actions: "Actions",
    // Ecologist Dashboard
    speciesManagement: "Species Management",
    conservationStatus: "Conservation Status",
    habitatAnalysis: "Habitat Analysis",
    researchNotes: "Research Notes",
    fieldObservations: "Field Observations",
    biodiversityIndex: "Biodiversity Index",
    ecosystemHealth: "Ecosystem Health",
    monitoringReports: "Monitoring Reports",
    addSpecies: "Add Species",
    editSpecies: "Edit Species",
    scientificName: "Scientific Name",
    commonName: "Common Name",
    habitat: "Habitat",
    population: "Population",
    threats: "Threats",
    conservationEfforts: "Conservation Efforts",
    // Staff Dashboard
    bookingManagement: "Booking Management",
    dailyOperations: "Daily Operations",
    visitorStatistics: "Visitor Statistics",
    facilityManagement: "Facility Management",
    staffScheduling: "Staff Scheduling",
    incidentReports: "Incident Reports",
    todayBookings: "Today's Bookings",
    pendingApprovals: "Pending Approvals",
    checkInVisitor: "Check-in Visitor",
    approveBooking: "Approve Booking",
    rejectBooking: "Reject Booking",
    cancelBooking: "Cancel Booking",
    // General
    overview: "Overview",
    statistics: "Statistics",
    reports: "Reports",
    management: "Management",
    settings: "Settings",
    searchUsers: "Search users...",
    searchSpecies: "Search species...",
    searchBookings: "Search bookings...",
  },
  Kinyarwanda: {
    dashboard: "Incamake",
    users: "Abakoresha",
    bookings: "Kubaka",
    species: "Ubwoko",
    reports: "Raporo Rusange",
    settings: "Igenamiterere",
    profile: "Umwirondoro",
    logout: "Sohoka",
    welcome: "Murakaza neza",
    statusOptimal: "Bisanzwe",
    search: "Shakisha...",
    myAccount: "Konti Yanjye",
    appearance: "Isura",
    system: "Sisitemu",
    privacy: "Umutekano",
    saveChanges: "Bika",
    revert: "Gusubira ku miterere",
    darkMode: "Uburyo bw'Ijoro",
    language: "Ururimi",
    timeZone: "Amasaha",
    dateFormat: "Imiterere y'Itariki",
    // Dashboard content
    myVisits: "Amazina Yanjye",
    upcoming: "Uza kugera",
    ecoPoints: "Amaponti y'Ecology",
    saved: "Abibumwe",
    history: "Amateka",
    nextMonth: "Ukwezi Kuzaza",
    locations: "Aho biherereye",
    myReservations: "Amabiko Yanjye",
    bookNewVisit: "Kubaka Urukurikane Ruphya",
    visitors: "Abagenzi",
    marshlandWatch: "Kureba Marshland",
    exploreWiki: "Kumenyesha Wiki",
    scientificCapture: "Kwiga Kwihangira",
    fieldObservation: "Kureba Mu Murima",
    capturedInMarshland: "Yafunzwe muri Marshland ecosystem",
    myBookings: "Amabiko Yanjye",
    checkAvailability: "Kureba Uburyo Bihari",
    approved: "YEMEWE",
    pending: "ITEGANYE",
    rejected: "KANZWE",
    cancelled: "KURWANYWE",
    // Admin Dashboard
    totalUsers: "Abakoresha Bose",
    activeUsers: "Abakoresha Bari Kuri Gukora",
    systemHealth: "Ubuzima Bwa Sisitemu",
    recentActivity: "Amahugurwa Mashya",
    userManagement: "Ukuyobora Abakoresha",
    systemReports: "Raporo Za Sisitemu",
    galleryManagement: "Ukuyobora Gallery",
    feedbackManagement: "Ukuyobora Ibisubizo",
    systemSettings: "Igenamiterere Za Sisitemu",
    allUsers: "Abakoresha Bose",
    addUser: "Ongeraho Umukoresha",
    editUser: "Hindura Umukoresha",
    deleteUser: "Siba Umukoresha",
    role: "Inshingano",
    status: "Imiterere",
    email: "Imeri",
    lastLogin: "Iwinjira Rya Nyuma",
    actions: "Igikorwa",
    // Ecologist Dashboard
    speciesManagement: "Ukuyobora Ubwoko",
    conservationStatus: "Imiterere Yo Kurinda",
    habitatAnalysis: "Ukusanya Amakuru Y'Ahantu Ho",
    researchNotes: "Inyandiko Zo Kwiga",
    fieldObservations: "Kureba Mu Murima",
    biodiversityIndex: "Ubwoko Bw'Ibinyabuzima",
    ecosystemHealth: "Ubuzima Bwa Ecosystem",
    monitoringReports: "Raporo Zo Kureba",
    addSpecies: "Ongeraho Ubwoko",
    editSpecies: "Hindura Ubwoko",
    scientificName: "Izina Ry'Ukwiga",
    commonName: "Izina Ryo Kwihangira",
    habitat: "Ahantu Ho",
    population: "Abaturage",
    threats: "Ibyangiza",
    conservationEfforts: "Gukora Akazi Ko Kurinda",
    // Staff Dashboard
    bookingManagement: "Ukuyobora Amabiko",
    dailyOperations: "Amahugurwa Bwa Buri Munsi",
    visitorStatistics: "Imibare Y'Abagenzi",
    facilityManagement: "Ukuyobora Ahantu",
    staffScheduling: "Guteka Abakozi",
    incidentReports: "Raporo Z'Ibyabaye",
    todayBookings: "Amabiko Ya Uyu Munsi",
    pendingApprovals: "Amabiko Ateganywe",
    checkInVisitor: "Kwiyandikisha Abagenzi",
    approveBooking: "Kemura Icyabitswe",
    rejectBooking: "Kana Icyabitswe",
    cancelBooking: "Kureka Icyabitswe",
    // General
    overview: "Igaragazambere",
    statistics: "Imibare",
    reports: "Raporo",
    management: "Ukuyobora",
    settings: "Igenamiterere",
    searchUsers: "Shakisha abakoresha...",
    searchSpecies: "Shakisha ubwoko...",
    searchBookings: "Shakisha amabiko...",
  },
  French: {
    dashboard: "Tableau de Bord",
    users: "Utilisateurs",
    bookings: "Réservations",
    species: "Espèces",
    reports: "Rapports Globaux",
    settings: "Paramètres",
    profile: "Profil",
    logout: "Déconnexion",
    welcome: "Bienvenue",
    statusOptimal: "Optimal",
    search: "Recherche Universelle...",
    myAccount: "Mon Compte",
    appearance: "Apparence",
    system: "Système",
    privacy: "Confidentialité",
    saveChanges: "Enregistrer",
    revert: "Réinitialiser",
    darkMode: "Mode Sombre",
    language: "Langue",
    timeZone: "Fuseau Horaire",
    dateFormat: "Format de Date",
    // Dashboard content
    myVisits: "Mes Visites",
    upcoming: "À Venir",
    ecoPoints: "Points Éco",
    saved: "Enregistrés",
    history: "Historique",
    nextMonth: "Le Mois Prochain",
    locations: "Lieux",
    myReservations: "Mes Réservations",
    bookNewVisit: "Réserver une Nouvelle Visite",
    visitors: "Visiteurs",
    marshlandWatch: "Surveillance Marécage",
    exploreWiki: "Explorer Wiki",
    scientificCapture: "Capture Scientifique",
    fieldObservation: "Observation sur le Terrain",
    capturedInMarshland: "Capturé dans l'écosystème marécageux",
    myBookings: "Mes Réservations",
    checkAvailability: "Vérifier la Disponibilité",
    approved: "APPROUVÉ",
    pending: "EN ATTENTE",
    rejected: "REJETÉ",
    cancelled: "ANNULÉ",
    // Admin Dashboard
    totalUsers: "Total Utilisateurs",
    activeUsers: "Utilisateurs Actifs",
    systemHealth: "Santé du Système",
    recentActivity: "Activité Récente",
    userManagement: "Gestion des Utilisateurs",
    systemReports: "Rapports Système",
    galleryManagement: "Gestion de la Galerie",
    feedbackManagement: "Gestion des Commentaires",
    systemSettings: "Paramètres Système",
    allUsers: "Tous les Utilisateurs",
    addUser: "Ajouter Utilisateur",
    editUser: "Modifier Utilisateur",
    deleteUser: "Supprimer Utilisateur",
    role: "Rôle",
    status: "Statut",
    email: "Email",
    lastLogin: "Dernière Connexion",
    actions: "Actions",
    // Ecologist Dashboard
    speciesManagement: "Gestion des Espèces",
    conservationStatus: "Statut de Conservation",
    habitatAnalysis: "Analyse de l'Habitat",
    researchNotes: "Notes de Recherche",
    fieldObservations: "Observations sur le Terrain",
    biodiversityIndex: "Indice de Biodiversité",
    ecosystemHealth: "Santé de l'Écosystème",
    monitoringReports: "Rapports de Surveillance",
    addSpecies: "Ajouter Espèce",
    editSpecies: "Modifier Espèce",
    scientificName: "Nom Scientifique",
    commonName: "Nom Commun",
    habitat: "Habitat",
    population: "Population",
    threats: "Menaces",
    conservationEfforts: "Efforts de Conservation",
    // Staff Dashboard
    bookingManagement: "Gestion des Réservations",
    dailyOperations: "Opérations Quotidiennes",
    visitorStatistics: "Statistiques des Visiteurs",
    facilityManagement: "Gestion des Installations",
    staffScheduling: "Planification du Personnel",
    incidentReports: "Rapports d'Incidents",
    todayBookings: "Réservations d'Aujourd'hui",
    pendingApprovals: "Approbations en Attente",
    checkInVisitor: "Enregistrer Visiteur",
    approveBooking: "Approuver Réservation",
    rejectBooking: "Rejeter Réservation",
    cancelBooking: "Annuler Réservation",
    // General
    overview: "Aperçu",
    statistics: "Statistiques",
    reports: "Rapports",
    management: "Gestion",
    settings: "Paramètres",
    searchUsers: "Rechercher des utilisateurs...",
    searchSpecies: "Rechercher des espèces...",
    searchBookings: "Rechercher des réservations...",
  }
};
